language: php

php:
  - 7.3
  - 7.4

before_script:
  - if ! git show-ref --quiet master; then
      git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/* ;
      git fetch --tags ;
      git branch master origin/master ;
    fi
  - composer install

# see https://github.com/travis-ci/travis-ci/issues/4942#issuecomment-159132444
git:
  depth: 99999

deploy:
  provider: releases
  api_key: $DEPLOY_TOKEN_SECURE
  file: dist/roave-backward-compatibility-check.phar
  # do not skip cleanup: if the repo is cleaned up when deploying, then the phar is gone as well.
  skip_cleanup: true
  on:
    tags: true

jobs:
  include:

    - stage: Static Analysis (src) with Psalm
      script: vendor/bin/psalm

    - stage: Static analysis (src) with phpstan
      script: vendor/bin/phpstan analyse

    - stage: Test
      script: vendor/bin/phpunit

    - stage: Code Coverage
      before_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - composer install
      script:
        - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml

    - stage: Coding Standards
      script: vendor/bin/phpcs

    - stage: Mutation Tests
      script: vendor/bin/infection --min-msi=100 --min-covered-msi=100

    - stage: Verify BC Breaks
      script: bin/roave-backward-compatibility-check --from=master --to=HEAD

    - stage: Build release PHAR
      script: ./build-phar.sh

cache:
  directories:
    - $HOME/.composer/cache
