language: php

before_script:
  - composer install

# see https://github.com/travis-ci/travis-ci/issues/4942#issuecomment-159132444
git:
  depth: 99999

jobs:
  include:
    - stage: Static analysis (src) with phpstan
      php: 7.2
      script: vendor/bin/phpstan analyse --level=7 src

    - stage: Test
      php: 7.2
      script: vendor/bin/phpunit

    - stage: Code Coverage
      php: 7.2
      before_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - composer install
      script:
        - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml

    - stage: Coding Standards
      php: 7.2
      script: vendor/bin/phpcs

    - stage: Mutation Tests
      php: 7.2
      script: vendor/bin/infection

cache:
  directories:
    - $HOME/.composer/cache
